openapi: 3.1.0
info:
  title: Coolify
  version: '0.1'
paths:
  /tags:
    get:
      tags:
        - Tags
      summary: List
      description: 'List all tags for the current team.'
      operationId: list-tags
      responses:
        '200':
          description: 'All tags for the current team.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
        '401':
          $ref: '#/components/responses/401'
        '400':
          $ref: '#/components/responses/400'
      security:
        -
          bearerAuth: []
